checking
dandelionadia/bootstrap-sass pull request #1
Opened 2018-01-30 12:44 UTC by dandelionadia

2018-01-30 14:09 UTC, kettanaito requested changes
Декілька зовсім малих змін. Загалом добре.

2018-01-30 14:09 UTC, kettanaito commented on src/styles/base/menu.scss
> +    &__link {
Розмежовуй сусідні селектори за допомогою порожньої лінії:
```sass
.some {
  &__foo {}

  &__another {}
}
```

2018-01-30 14:09 UTC, kettanaito commented on src/styles/components/preview.scss
> +
Забагато порожніх рядків. Має бути 1.

2018-01-31 20:26 UTC, kettanaito requested changes

2018-01-31 20:26 UTC, kettanaito commented on index.html
> +<html>
`<html lang="en">`

2018-01-31 20:26 UTC, kettanaito commented on src/styles/components/block-black.scss
> +  &__content {}
Empty css selectors must be removed.

2018-01-31 20:26 UTC, kettanaito commented on src/styles/variables.scss
> +$color-white: white;
Prefer hex colors (i.e. `#fff`) over keywords (`black`, `white`).

2018-02-03 16:50 UTC, kettanaito requested changes

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +  <div class="hat">
"hat" це шляпа. Придумай кращу назву для блоку.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +            <div class="hat__information">
`hat__content` стисліше а те саме.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +              <p class="hat__heading">Porempopem</p>
Параграф не може бути заголовком ("heading"). Використовуй правильний тег заголовку.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +              <h1>obectipe</h1>
Мабуть це мало бути заголовком??

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +              <img src="" alt="">
Порожня картинка?

2018-02-03 16:50 UTC, kettanaito commented on src/styles/components/hat.scss
> +    opacity: 70;
Значення прозорості від 1 до 0. Виправ.

2018-02-03 16:50 UTC, kettanaito commented on src/styles/components/hat.scss
> +    background-color: transparentize(#776957 /*#A9B2D2*/, .4);
Прибери закоментований колір.

2018-02-03 16:50 UTC, kettanaito commented on src/styles/components/hat.scss
> +    color: $color-white;
Тут і на 29 повторення кольору.
Задай колір батьківському елементу, дочерні внаслідують.

2018-02-03 16:50 UTC, kettanaito commented on src/styles/main.scss
> +@import 'components/hat';
Краща назва.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +              <p>lorem</p>
Придай хочаб якись текст будь ласка.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +              <p class="hat__text">Whot We Do</p>
Чому це параграф внєзапно "hat__text", а інші параграфи в цьому ж блоці - ні?
Переосмисли чи клас тут потрібен взагалі.

2018-02-03 16:50 UTC, kettanaito commented on index.html
> +          <div class="col-md-12">
Що щодо інших розмірів екранів, респонсів?

2018-02-03 16:56 UTC, kettanaito requested changes

2018-02-03 16:56 UTC, kettanaito commented on src/styles/base/menu.scss
> +  &__x {
що таке "х"? Будь ласка чіткі назви класів, що показують суть елементу.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/base/menu.scss
> +    color: $color-black;
А інший текст не має бути чорний?
Скоріше за все перемісти колір до батьківського елементу.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/base/menu.scss
> +    padding: 0 10px 0 10px;
Це те саме що `padding: 0 10px`.
Значення деяких властивостей повторюються автоматично.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/block-black.scss
> +    color: $color-white;
Тільки заголовок має бути білим? Чи весь текст?
Завжди починай із батьківського елементу.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/block-logo.scss
> +.block-logo-top {
Що таке "block"?
Будь ласка чіткі назви класів.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/foo.scss
> +.rp {
Що таке "rp"?

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/greeting.scss
> +  &__heading {
Відступ між батьківським і дочернім правилом в сас.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/greeting.scss
> +  &__text {
Відступ перед правилом.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/hat.scss
> +  &__eye {
Можливо краще "__badge". Не прив"язуєшся до того, що в баджі.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/components/services.scss
> +  &__content{
Відступ між селектором і фігурними дужками.

2018-02-03 16:56 UTC, kettanaito commented on src/templates/index.njk
> +<!DOCTYPE html>
Якщо цей файл непотрібний - видали.

2018-02-03 16:56 UTC, kettanaito commented on src/styles/main.scss
> +@import 'components/block-black';
Не став повсюди "block", це нічого не описує, а місце займає.

2018-02-03 18:03 UTC, dandelionadia commented on src/styles/components/block-black.scss
> +    color: $color-white;
Лише заголовок має бути білим.
Текст має колір сірий як і весь основний текст сторінки.

2018-02-04 10:15 UTC, kettanaito requested changes

2018-02-04 10:15 UTC, kettanaito commented on index.html
> +            <div class="col-md-12 ">
Якщо однакової величини на всіх екранах то задай від  `col-xs-`.

2018-02-04 10:15 UTC, kettanaito commented on index.html
> +      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
Класи колонок в бутстрапі пишуться від найменшого екрану до найбільшого, зліва направо.
Має бути `col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3`

2018-02-04 10:15 UTC, kettanaito commented on index.html
> +        <div class="services">
Так як у тебе декілька цих блоків, мабуть краще назвати їх `service` (однина).
`services` було б умісно задати одному батьківському контейнеру, всередині якого список всіх послуг.

2018-02-04 10:15 UTC, kettanaito commented on src/styles/base/menu.scss
> +  // псевдоклас при наведнні мишкою силка змінює колір
Відступ.

2018-02-04 10:15 UTC, kettanaito commented on src/styles/base/typography.scss
> +h1,
Відступ.

2018-02-07 08:50 UTC, kettanaito requested changes
:)

2018-02-07 08:50 UTC, kettanaito commented on index.html
> +            <div class="col-xs-12 ">
Прибери будь ласка зайвий пробіл після класу колонки.

2018-02-07 09:00 UTC, kettanaito approved these changes

2018-02-07 09:01 UTC, merged